# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "generic/ubuntu2004"
    config.vm.hostname = "golang"
    config.vm.synced_folder "./../..", "/vagrant", type: "nfs"
    config.vm.provision :shell, path: "./../provision.sh"
    config.vm.network "forwarded_port", guest: 3018, host: 3018

    config.vm.provider :libvirt do |v|
      v.default_prefix = "golang"
    end

  end